In [2]:
import pandas as pd
df = pd.read_csv("2026dependenciesHWFile.csv")
df.head()

,course,courseLetter,courseNumber,relatedTo,relatedToCourseLetter,relatedToCourseNumber,How,Unnamed: 7,courseDictionary,courseLetter.1,courseNumber.1
0,AME 105,AME,105,MUH 105,MUH,105,CrossList,NaN,AME 105,AME,105
1,AME 105,AME,105,Cultural Perspectives,NaN,NaN,GenEd,NaN,AME 121,AME,121
2,AME 105,AME,105,Fine Arts,NaN,NaN,GenEd,NaN,AME 122,AME,122
3,AME 105,AME,105,Humanities,NaN,NaN,GenEd,NaN,AME 205,AME,205
4,AME 121,AME,121,American Studies Minor,NaN,NaN,Checksheet,NaN,AME 264,AME,264

In [3]:
df.shape

(6090, 11)

In [4]:
df.columns

Index(['course', 'courseLetter', 'courseNumber', 'relatedTo',
       'relatedToCourseLetter', 'relatedToCourseNumber', 'How', 'Unnamed: 7',
       'courseDictionary', 'courseLetter.1', 'courseNumber.1'],
      dtype='str')

In [5]:
df.isna()

,course,courseLetter,courseNumber,relatedTo,relatedToCourseLetter,relatedToCourseNumber,How,Unnamed: 7,courseDictionary,courseLetter.1,courseNumber.1
0,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,True,True,False,True,False,False,False
2,False,False,False,False,True,True,False,True,False,False,False
3,False,False,False,False,True,True,False,True,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
6085,False,False,False,False,True,True,False,True,True,True,True
6086,False,False,False,False,True,True,False,True,True,True,True
6087,False,False,False,False,True,True,False,True,True,True,True
6088,False,False,False,False,True,True,False,True,True,True,True
6089,False,False,False,False,True,True,False,True,True,True,True

In [10]:
# cis_total = df["course"].count()
# print(cis_total)
# df[df["course"] == "CIS 100"]
df[df["course"] == "CIS 100"].count()

course                   11
courseLetter             11
courseNumber             11
relatedTo                11
relatedToCourseLetter     6
relatedToCourseNumber     6
How                      11
Unnamed: 7                0
courseDictionary         11
courseLetter.1           11
courseNumber.1           11
dtype: int64